### ISSUE TITLE
Update Semantic-ui to latest (2.4.2)

### ISSUE THREAD

**Issue by felixmosh** [RTLCSS/cdn#1]
Hi, 

There is any way to update the version of semantic-ui to latest? (2.4.2)

**Comment by felixmosh** [comment]
I can make a PR if you explain what should I run :]

**Comment by MohammadYounes** [comment]
All is needed is to rebase the repo https://github.com/RTLCSS/Semantic-UI and build with [`rtl:true`](https://github.com/RTLCSS/Semantic-UI/commit/9da447f3acd185dc319683cc19970322c948e915#diff-3d9cf0d4f4b4ed716dc2cbafbe81118dL17).

**Comment by MohammadYounes** [comment]
https://rtlcss.com/cdn/css-frameworks/semantic-ui/#version-2-4-1
